### ISSUE TITLE
[InvalidArgumentException]   Could not find package acquia/df-project with version ^8.1.0.

### ISSUE THREAD

**Issue by kieranacquia** [acquia/df-project#1]
I get the following when I follow the instructions:

> $ composer create-project acquia/df-project:^8.1.0 MY_PROJECT
> [InvalidArgumentException]
>   Could not find package acquia/df-project with version ^8.1.0.
> 
> composer create-project acquia/df-project:^8._-1._ MY_PROJECT
>  [UnexpectedValueException]
>   Could not parse version constraint ^8._-1._: Invalid version string "^8._-1._"

**Comment by dieguit** [comment]
Same happens with:
composer create-project acquia/df-project:^8.1.0 MYPROJECT --no-interaction --repository=https://packages.drupal.org/8

Cloning the project and running **composer install**, composer fails with this message:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - drupal/leaflet 8.1.x-dev requires leaflet/leaflet ^0.7.7 -> no matching package found.
>     - drupal/df dev-8.x-1.x requires drupal/leaflet 8.1.x-dev -> satisfiable by drupal/leaflet[8.1.x-dev].
>     - Installation request for drupal/df dev-8.x-1.x -> satisfiable by drupal/df[dev-8.x-1.x].

**Comment by epfremmer** [comment]
Removing the df-project constraint and adding `--stability dev` flag to the command allows the installation to continue.

``` bash
composer create-project acquia/df-project MY_PROJECT --no-interaction --stability dev
```

It looks like they have not created any tags for this project in packagist.org so composer can't find the correct stable version to install. 

The installation then blows up as dieguit mentioned above because it is not able to find the leaflet/leaflet dependency. I tested specifying the leaflet package manually in composer.json as found in http://cgit.drupalcode.org/leaflet/tree/composer.json?h=8.x-1.x which seems to resolve the dependency issue.

**Comment by saltednut** [comment]
This should be resolved now (sorry for the delay) - let us know if you're still having issues.
